### ISSUE TITLE
Example bakonf.yml produces error

### ISSUE THREAD

**Issue by jose1711** [iustin/bakonf#2]
https://github.com/iustin/bakonf/blob/9d8018789bb8dcc9732c4e5b8753fa00378a7115/bakonf.yml#L2

`configs` entry in config file is treated as a list which causes the example config file to produce an error:
```
Traceback (most recent call last):
  File "/usr/bin/bakonf", line 1079, in <module>
    main()
  File "/usr/bin/bakonf", line 1070, in main
    real_main()
  File "/usr/bin/bakonf", line 1063, in real_main
    bm = BackupManager(options)
  File "/usr/bin/bakonf", line 706, in __init__
    self._parseconf(options.configfile)
  File "/usr/bin/bakonf", line 765, in _parseconf
    tlist = self._get_extra_sources(filename, config)
  File "/usr/bin/bakonf", line 732, in _get_extra_sources
    with open(fname) as stream:
IsADirectoryError: [Errno 21] Is a directory: '/'
```
In order to fix this the line needs to be changed to a single-item list, e. g. like this:
```
configs:
- /etc/bakonf/conf.d/*.yml
```

**Comment by iustin** [comment]
I'll try to make a release will both fixes and also the pending commits sometimes next weekend or so. Thanks!
